# Generated by Django 2.2.7 on 2019-11-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discription',
            field=models.CharField(default='details', max_length=800),
        ),
    ]
