# Generated by Django 2.2.7 on 2019-11-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discription',
            field=models.TextField(),
        ),
    ]
