# Generated by Django 2.2.7 on 2019-11-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20191121_0538'),
    ]

    operations = [
    ]
