# Generated by Django 2.2.4 on 2019-12-05 19:52

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_orderitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price_large',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price_small',
        ),
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.TextField(default=orders.models.image),
        ),
    ]
