# Generated by Django 2.2.4 on 2019-12-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20191205_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
