# Generated by Django 2.2.4 on 2019-12-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20191205_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Toppings',
        ),
    ]
